
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /sw
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
spring:
  datasource:
    url: jdbc:mysql://ec2-3-12-88-45.us-east-2.compute.amazonaws.com:3306/hrm
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: com.spring.hrm_project.common.naming.CustomPhysicalNamingStrategy